/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardQualityRouteImport } from './routes/dashboard.quality'
import { Route as DashboardOperationsRouteImport } from './routes/dashboard.operations'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardQualityIndexRouteImport } from './routes/dashboard.quality.index'
import { Route as DashboardOperationsIndexRouteImport } from './routes/dashboard.operations.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardQualitySkuInvestigationRouteImport } from './routes/dashboard.quality.sku-investigation'
import { Route as DashboardQualitySettingsRouteImport } from './routes/dashboard.quality.settings'
import { Route as DashboardQualityFeedbackRouteImport } from './routes/dashboard.quality.feedback'
import { Route as DashboardQualityFailureAnalysisRouteImport } from './routes/dashboard.quality.failure-analysis'
import { Route as DashboardQualityAlertsRouteImport } from './routes/dashboard.quality.alerts'
import { Route as DashboardOperationsSkuRouteImport } from './routes/dashboard.operations.sku'
import { Route as DashboardOperationsSettingsRouteImport } from './routes/dashboard.operations.settings'
import { Route as DashboardOperationsReportsRouteImport } from './routes/dashboard.operations.reports'
import { Route as DashboardOperationsIntegrationsRouteImport } from './routes/dashboard.operations.integrations'
import { Route as DashboardOperationsAnalyticsRouteImport } from './routes/dashboard.operations.analytics'
import { Route as DashboardOperationsAlertsRouteImport } from './routes/dashboard.operations.alerts'
import { Route as DashboardOperationsActionCenterRouteImport } from './routes/dashboard.operations.action-center'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSystemRouteImport } from './routes/dashboard.admin.system'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminBillingRouteImport } from './routes/dashboard.admin.billing'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQualityRoute = DashboardQualityRouteImport.update({
  id: '/dashboard/quality',
  path: '/dashboard/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: '/dashboard/operations',
  path: '/dashboard/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQualityIndexRoute = DashboardQualityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardQualityRoute,
} as any)
const DashboardOperationsIndexRoute =
  DashboardOperationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardQualitySkuInvestigationRoute =
  DashboardQualitySkuInvestigationRouteImport.update({
    id: '/sku-investigation',
    path: '/sku-investigation',
    getParentRoute: () => DashboardQualityRoute,
  } as any)
const DashboardQualitySettingsRoute =
  DashboardQualitySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardQualityRoute,
  } as any)
const DashboardQualityFeedbackRoute =
  DashboardQualityFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => DashboardQualityRoute,
  } as any)
const DashboardQualityFailureAnalysisRoute =
  DashboardQualityFailureAnalysisRouteImport.update({
    id: '/failure-analysis',
    path: '/failure-analysis',
    getParentRoute: () => DashboardQualityRoute,
  } as any)
const DashboardQualityAlertsRoute = DashboardQualityAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardQualityRoute,
} as any)
const DashboardOperationsSkuRoute = DashboardOperationsSkuRouteImport.update({
  id: '/sku',
  path: '/sku',
  getParentRoute: () => DashboardOperationsRoute,
} as any)
const DashboardOperationsSettingsRoute =
  DashboardOperationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsReportsRoute =
  DashboardOperationsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsIntegrationsRoute =
  DashboardOperationsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsAnalyticsRoute =
  DashboardOperationsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsAlertsRoute =
  DashboardOperationsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardOperationsActionCenterRoute =
  DashboardOperationsActionCenterRouteImport.update({
    id: '/action-center',
    path: '/action-center',
    getParentRoute: () => DashboardOperationsRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSystemRoute = DashboardAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminBillingRoute = DashboardAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/operations': typeof DashboardOperationsRouteWithChildren
  '/dashboard/quality': typeof DashboardQualityRouteWithChildren
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/system': typeof DashboardAdminSystemRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/operations/action-center': typeof DashboardOperationsActionCenterRoute
  '/dashboard/operations/alerts': typeof DashboardOperationsAlertsRoute
  '/dashboard/operations/analytics': typeof DashboardOperationsAnalyticsRoute
  '/dashboard/operations/integrations': typeof DashboardOperationsIntegrationsRoute
  '/dashboard/operations/reports': typeof DashboardOperationsReportsRoute
  '/dashboard/operations/settings': typeof DashboardOperationsSettingsRoute
  '/dashboard/operations/sku': typeof DashboardOperationsSkuRoute
  '/dashboard/quality/alerts': typeof DashboardQualityAlertsRoute
  '/dashboard/quality/failure-analysis': typeof DashboardQualityFailureAnalysisRoute
  '/dashboard/quality/feedback': typeof DashboardQualityFeedbackRoute
  '/dashboard/quality/settings': typeof DashboardQualitySettingsRoute
  '/dashboard/quality/sku-investigation': typeof DashboardQualitySkuInvestigationRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/quality/': typeof DashboardQualityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/system': typeof DashboardAdminSystemRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/operations/action-center': typeof DashboardOperationsActionCenterRoute
  '/dashboard/operations/alerts': typeof DashboardOperationsAlertsRoute
  '/dashboard/operations/analytics': typeof DashboardOperationsAnalyticsRoute
  '/dashboard/operations/integrations': typeof DashboardOperationsIntegrationsRoute
  '/dashboard/operations/reports': typeof DashboardOperationsReportsRoute
  '/dashboard/operations/settings': typeof DashboardOperationsSettingsRoute
  '/dashboard/operations/sku': typeof DashboardOperationsSkuRoute
  '/dashboard/quality/alerts': typeof DashboardQualityAlertsRoute
  '/dashboard/quality/failure-analysis': typeof DashboardQualityFailureAnalysisRoute
  '/dashboard/quality/feedback': typeof DashboardQualityFeedbackRoute
  '/dashboard/quality/settings': typeof DashboardQualitySettingsRoute
  '/dashboard/quality/sku-investigation': typeof DashboardQualitySkuInvestigationRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/operations': typeof DashboardOperationsIndexRoute
  '/dashboard/quality': typeof DashboardQualityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/operations': typeof DashboardOperationsRouteWithChildren
  '/dashboard/quality': typeof DashboardQualityRouteWithChildren
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/system': typeof DashboardAdminSystemRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/operations/action-center': typeof DashboardOperationsActionCenterRoute
  '/dashboard/operations/alerts': typeof DashboardOperationsAlertsRoute
  '/dashboard/operations/analytics': typeof DashboardOperationsAnalyticsRoute
  '/dashboard/operations/integrations': typeof DashboardOperationsIntegrationsRoute
  '/dashboard/operations/reports': typeof DashboardOperationsReportsRoute
  '/dashboard/operations/settings': typeof DashboardOperationsSettingsRoute
  '/dashboard/operations/sku': typeof DashboardOperationsSkuRoute
  '/dashboard/quality/alerts': typeof DashboardQualityAlertsRoute
  '/dashboard/quality/failure-analysis': typeof DashboardQualityFailureAnalysisRoute
  '/dashboard/quality/feedback': typeof DashboardQualityFeedbackRoute
  '/dashboard/quality/settings': typeof DashboardQualitySettingsRoute
  '/dashboard/quality/sku-investigation': typeof DashboardQualitySkuInvestigationRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/operations/': typeof DashboardOperationsIndexRoute
  '/dashboard/quality/': typeof DashboardQualityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/change-password'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/operations'
    | '/dashboard/quality'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/system'
    | '/dashboard/admin/users'
    | '/dashboard/operations/action-center'
    | '/dashboard/operations/alerts'
    | '/dashboard/operations/analytics'
    | '/dashboard/operations/integrations'
    | '/dashboard/operations/reports'
    | '/dashboard/operations/settings'
    | '/dashboard/operations/sku'
    | '/dashboard/quality/alerts'
    | '/dashboard/quality/failure-analysis'
    | '/dashboard/quality/feedback'
    | '/dashboard/quality/settings'
    | '/dashboard/quality/sku-investigation'
    | '/dashboard/admin/'
    | '/dashboard/operations/'
    | '/dashboard/quality/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/change-password'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/register'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/system'
    | '/dashboard/admin/users'
    | '/dashboard/operations/action-center'
    | '/dashboard/operations/alerts'
    | '/dashboard/operations/analytics'
    | '/dashboard/operations/integrations'
    | '/dashboard/operations/reports'
    | '/dashboard/operations/settings'
    | '/dashboard/operations/sku'
    | '/dashboard/quality/alerts'
    | '/dashboard/quality/failure-analysis'
    | '/dashboard/quality/feedback'
    | '/dashboard/quality/settings'
    | '/dashboard/quality/sku-investigation'
    | '/dashboard/admin'
    | '/dashboard/operations'
    | '/dashboard/quality'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/change-password'
    | '/contact'
    | '/features'
    | '/login'
    | '/pricing'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/operations'
    | '/dashboard/quality'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/system'
    | '/dashboard/admin/users'
    | '/dashboard/operations/action-center'
    | '/dashboard/operations/alerts'
    | '/dashboard/operations/analytics'
    | '/dashboard/operations/integrations'
    | '/dashboard/operations/reports'
    | '/dashboard/operations/settings'
    | '/dashboard/operations/sku'
    | '/dashboard/quality/alerts'
    | '/dashboard/quality/failure-analysis'
    | '/dashboard/quality/feedback'
    | '/dashboard/quality/settings'
    | '/dashboard/quality/sku-investigation'
    | '/dashboard/admin/'
    | '/dashboard/operations/'
    | '/dashboard/quality/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardOperationsRoute: typeof DashboardOperationsRouteWithChildren
  DashboardQualityRoute: typeof DashboardQualityRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quality': {
      id: '/dashboard/quality'
      path: '/dashboard/quality'
      fullPath: '/dashboard/quality'
      preLoaderRoute: typeof DashboardQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/operations': {
      id: '/dashboard/operations'
      path: '/dashboard/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quality/': {
      id: '/dashboard/quality/'
      path: '/'
      fullPath: '/dashboard/quality/'
      preLoaderRoute: typeof DashboardQualityIndexRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/operations/': {
      id: '/dashboard/operations/'
      path: '/'
      fullPath: '/dashboard/operations/'
      preLoaderRoute: typeof DashboardOperationsIndexRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/quality/sku-investigation': {
      id: '/dashboard/quality/sku-investigation'
      path: '/sku-investigation'
      fullPath: '/dashboard/quality/sku-investigation'
      preLoaderRoute: typeof DashboardQualitySkuInvestigationRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/quality/settings': {
      id: '/dashboard/quality/settings'
      path: '/settings'
      fullPath: '/dashboard/quality/settings'
      preLoaderRoute: typeof DashboardQualitySettingsRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/quality/feedback': {
      id: '/dashboard/quality/feedback'
      path: '/feedback'
      fullPath: '/dashboard/quality/feedback'
      preLoaderRoute: typeof DashboardQualityFeedbackRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/quality/failure-analysis': {
      id: '/dashboard/quality/failure-analysis'
      path: '/failure-analysis'
      fullPath: '/dashboard/quality/failure-analysis'
      preLoaderRoute: typeof DashboardQualityFailureAnalysisRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/quality/alerts': {
      id: '/dashboard/quality/alerts'
      path: '/alerts'
      fullPath: '/dashboard/quality/alerts'
      preLoaderRoute: typeof DashboardQualityAlertsRouteImport
      parentRoute: typeof DashboardQualityRoute
    }
    '/dashboard/operations/sku': {
      id: '/dashboard/operations/sku'
      path: '/sku'
      fullPath: '/dashboard/operations/sku'
      preLoaderRoute: typeof DashboardOperationsSkuRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/settings': {
      id: '/dashboard/operations/settings'
      path: '/settings'
      fullPath: '/dashboard/operations/settings'
      preLoaderRoute: typeof DashboardOperationsSettingsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/reports': {
      id: '/dashboard/operations/reports'
      path: '/reports'
      fullPath: '/dashboard/operations/reports'
      preLoaderRoute: typeof DashboardOperationsReportsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/integrations': {
      id: '/dashboard/operations/integrations'
      path: '/integrations'
      fullPath: '/dashboard/operations/integrations'
      preLoaderRoute: typeof DashboardOperationsIntegrationsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/analytics': {
      id: '/dashboard/operations/analytics'
      path: '/analytics'
      fullPath: '/dashboard/operations/analytics'
      preLoaderRoute: typeof DashboardOperationsAnalyticsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/alerts': {
      id: '/dashboard/operations/alerts'
      path: '/alerts'
      fullPath: '/dashboard/operations/alerts'
      preLoaderRoute: typeof DashboardOperationsAlertsRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/operations/action-center': {
      id: '/dashboard/operations/action-center'
      path: '/action-center'
      fullPath: '/dashboard/operations/action-center'
      preLoaderRoute: typeof DashboardOperationsActionCenterRouteImport
      parentRoute: typeof DashboardOperationsRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/system': {
      id: '/dashboard/admin/system'
      path: '/system'
      fullPath: '/dashboard/admin/system'
      preLoaderRoute: typeof DashboardAdminSystemRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/billing': {
      id: '/dashboard/admin/billing'
      path: '/billing'
      fullPath: '/dashboard/admin/billing'
      preLoaderRoute: typeof DashboardAdminBillingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBillingRoute: typeof DashboardAdminBillingRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminSystemRoute: typeof DashboardAdminSystemRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBillingRoute: DashboardAdminBillingRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminSystemRoute: DashboardAdminSystemRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardOperationsRouteChildren {
  DashboardOperationsActionCenterRoute: typeof DashboardOperationsActionCenterRoute
  DashboardOperationsAlertsRoute: typeof DashboardOperationsAlertsRoute
  DashboardOperationsAnalyticsRoute: typeof DashboardOperationsAnalyticsRoute
  DashboardOperationsIntegrationsRoute: typeof DashboardOperationsIntegrationsRoute
  DashboardOperationsReportsRoute: typeof DashboardOperationsReportsRoute
  DashboardOperationsSettingsRoute: typeof DashboardOperationsSettingsRoute
  DashboardOperationsSkuRoute: typeof DashboardOperationsSkuRoute
  DashboardOperationsIndexRoute: typeof DashboardOperationsIndexRoute
}

const DashboardOperationsRouteChildren: DashboardOperationsRouteChildren = {
  DashboardOperationsActionCenterRoute: DashboardOperationsActionCenterRoute,
  DashboardOperationsAlertsRoute: DashboardOperationsAlertsRoute,
  DashboardOperationsAnalyticsRoute: DashboardOperationsAnalyticsRoute,
  DashboardOperationsIntegrationsRoute: DashboardOperationsIntegrationsRoute,
  DashboardOperationsReportsRoute: DashboardOperationsReportsRoute,
  DashboardOperationsSettingsRoute: DashboardOperationsSettingsRoute,
  DashboardOperationsSkuRoute: DashboardOperationsSkuRoute,
  DashboardOperationsIndexRoute: DashboardOperationsIndexRoute,
}

const DashboardOperationsRouteWithChildren =
  DashboardOperationsRoute._addFileChildren(DashboardOperationsRouteChildren)

interface DashboardQualityRouteChildren {
  DashboardQualityAlertsRoute: typeof DashboardQualityAlertsRoute
  DashboardQualityFailureAnalysisRoute: typeof DashboardQualityFailureAnalysisRoute
  DashboardQualityFeedbackRoute: typeof DashboardQualityFeedbackRoute
  DashboardQualitySettingsRoute: typeof DashboardQualitySettingsRoute
  DashboardQualitySkuInvestigationRoute: typeof DashboardQualitySkuInvestigationRoute
  DashboardQualityIndexRoute: typeof DashboardQualityIndexRoute
}

const DashboardQualityRouteChildren: DashboardQualityRouteChildren = {
  DashboardQualityAlertsRoute: DashboardQualityAlertsRoute,
  DashboardQualityFailureAnalysisRoute: DashboardQualityFailureAnalysisRoute,
  DashboardQualityFeedbackRoute: DashboardQualityFeedbackRoute,
  DashboardQualitySettingsRoute: DashboardQualitySettingsRoute,
  DashboardQualitySkuInvestigationRoute: DashboardQualitySkuInvestigationRoute,
  DashboardQualityIndexRoute: DashboardQualityIndexRoute,
}

const DashboardQualityRouteWithChildren =
  DashboardQualityRoute._addFileChildren(DashboardQualityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardOperationsRoute: DashboardOperationsRouteWithChildren,
  DashboardQualityRoute: DashboardQualityRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
